### ISSUE TITLE
[BUG] Repeating error

### ISSUE THREAD

**Issue by thething42** [ChandlerFerry/deafwave-blockchain#9] opened 2021-07-02 06:25 UTC
**Describe the bug**
2021-07-01T23:24:32.651 full_node deafwave.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-07-01T23:24:37.146 full_node full_node_server        : INFO     Connected with introducer {'host': 'beta2_introducer.deafwave.net', 'port': 58620}
2021-07-01T23:24:37.214 full_node full_node_server        : INFO     Connection closed: beta2_introducer.deafwave.net, node id: 6bf7d6cf3a67f4017255cfa54bb607c3cddab7b59d5a57cffbf5e68a668ae72f
2021-07-01T23:24:37.215 full_node deafwave.full_node.full_node: INFO     peer disconnected {'host': '97.126.106.67', 'port': 58620}
2021-07-01T23:24:37.215 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '97.126.106.67', 'port': 58620}. Traceback (most recent call last):
  File "deafwave\server\server.py", line 579, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**To Reproduce**
launch deafcoin

View logs

- OS: Win10

**Comment by bithadder** [comment] 2021-07-02 06:31
I got similar error while launching the GUI, not synced
OS : Ubuntu Server 20 with Gnome Desktop
```
`2021-07-02T13:28:57.676 full_node deafwave.full_node.full_node: INFO     peer disconnected None
2021-07-02T13:29:11.938 full_node deafwave.full_node.full_node: INFO     Received 1 peers from DNS seeder.
2021-07-02T13:29:22.227 full_node full_node_server        : INFO     Connected with introducer {'host': 'beta2_introducer.deafwave.net', 'port': 58620}
2021-07-02T13:29:22.726 full_node full_node_server        : INFO     Connection closed: beta2_introducer.deafwave.net, node id: 6bf7d6cf3a67f4017255cfa54bb607c3cddab7b59d5a57cffbf5e68a668ae72f
2021-07-02T13:29:22.726 full_node deafwave.full_node.full_node: INFO     peer disconnected None
2021-07-02T13:29:28.584 full_node full_node_server        : INFO     Connected with full_node {'host': '192.180.138.101', 'port': 58620}
2021-07-02T13:29:43.564 full_node full_node_server        : INFO     Connected with introducer {'host': 'beta2_introducer.deafwave.net', 'port': 58620}
2021-07-02T13:29:44.046 full_node full_node_server        : INFO     Connection closed: beta2_introducer.deafwave.net, node id: 6bf7d6cf3a67f4017255cfa54bb607c3cddab7b59d5a57cffbf5e68a668ae72f

````

**Comment by ChandlerFerry** [comment] 2021-07-02 19:34
Closing as a duplicate of #8

**Closed by ChandlerFerry** 2021-07-02 19:34 UTC
Labels: bug
